sudo: required
services:
  - docker

before_install:
  - docker build -t hoffnung8493/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hoffnung8493/react-test npm test
after_success:
  - docker build -t hoffnung8493/multi-client ./client
  - docker build -t hoffnung8493/multi-nginx ./nginx
  - docker build -t hoffnung8493/multi-server ./server
  - docker build -t hoffnung8493/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hoffnung8493/multi-client
  - docker push hoffnung8493/multi-nginx
  - docker push hoffnung8493/multi-server
  - docker push hoffnung8493/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-2-904358639036
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
